StackName: todo-stack

TemplateBody:
  # You can either define the whole template body inline or you can include
  # a reference to an external template file. TemplateBody has to be a string,
  # so Fn::Stringify helps with that.
  Fn::Stringify: !Include todo-stack-template.yml

Capabilities: [CAPABILITY_IAM]
